### ISSUE TITLE
Print sample log to stderr instead of stdout

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-bittorrent#110]
Was going through stage 1 failures, and looks like a good number of people just get confused by the log statement interfering with checks: 

<img width="935" alt="Screenshot 2024-10-19 at 21 07 28" src="https://github.com/user-attachments/assets/72ea2267-d91c-4e89-be42-2020b27d1e09">

Let's tackle this next week @andy1li

**Comment by andy1li** [comment]
Closed by [CC-1469: Change all sample logs to print to stderr instead of stdout](https://linear.app/codecrafters/issue/CC-1469/change-all-sample-logs-to-print-to-stderr-instead-of-stdout)
